import React from "react";
import "./masonry.css";

const Masonry = () => {
  return (
    <div className="bg-black">
      <div className="sm:mx-40 mx-10 py-20">
        <h1 className="font-bold text-white text-center sm:text-[50px] text-[30px] leading-[60px]">
          Popular NFT's generated by Artists
        </h1>
        <p className="font-normal text-white text-center pt-3 sm:text-[25.29px] text-[17px] leading-[29px]">
          We try to keep returns and exchanges as simple as possible. As long as
          they meet our criteria, it should be no problem at all to return or
          exchange them.
        </p>
      </div>
      <div class="  sm:mx-40 mx-10  min-h-screen p-2">
        <div class="grid grid-cols-4 gap-4">
          <div className=" row-span-1 img1">
            {/* <img class="h-full max-w-full rounded-lg" src={img1} alt="" /> */}
          </div>
          <div className="col-span-2 img2">
            {/* <img
              class="h-full max-w-full col-span-6 rounded-lg"
              src={img2}
              alt=""
            /> */}
          </div>
          <div className="img3">
            {/* <img
              class="h-full max-w-full col-span-3 rounded-lg"
              src="https://flowbite.s3.amazonaws.com/docs/gallery/square/image-2.jpg"
              alt=""
            /> */}
          </div>
          <div className="col-span-2  row-span-1 img4 ">
            {/* <img
              class="h-[40vh] w-full rounded-lg"
              src="https://flowbite.s3.amazonaws.com/docs/gallery/square/image-3.jpg"
              alt=""
            /> */}
          </div>
          <div className="img5">
            {/* <img
              class="h-full max-w-full rounded-lg"
              src="https://flowbite.s3.amazonaws.com/docs/gallery/square/image-4.jpg"
              alt=""
            /> */}
          </div>

          <div className="img6">
            {/* <img
              class="h-full max-w-full rounded-lg"
              src="https://flowbite.s3.amazonaws.com/docs/gallery/square/image-11.jpg"
              alt=""
            /> */}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Masonry;
